### ISSUE TITLE
Automated release of `@tsd/typescript` v5.0 failed

### ISSUE THREAD

**Issue by mrazauskas** [SamVerschueren/tsd#188]
Looks like patch logic should be tweaked, because the automated release of `@tsd/typescript` v5.0 failed.

Posting it here for more visibility: https://github.com/SamVerschueren/tsd-typescript/actions/runs/4440293420

**Comment by tommy-mitchell** [comment]
Seems like this is resolved: https://github.com/SamVerschueren/tsd-typescript/issues/5#issuecomment-1473359117

**Comment by mrazauskas** [comment]
Yep. I see new commits were push 30mins ago and this is not fixed.
